### ISSUE TITLE
Christmas wish (Request): Support for iTunes/Apple Music

### ISSUE THREAD

**Issue by fabi94music** [kmikiy/SpotMenu#33]
Hey, 
we talked about it so I thought to open an extra issue/request.  :)
Would be very nice :) ❤️ As I occasionally switch between my iTunes library and Spotify :) 🎵
Thank you for considering it. 👍

**Comment by fabi94music** [comment]
The player I used before I discovered SpotMenu was "MiniPlay" from Denys Star (twitter: @zyafa) which can handle both iTunes/Apple Music and Spotify. However the development of app seem to be stopped. Maybe Denys could help to implement AppleMusic/iTunes support.

**Comment by fabi94music** [comment]
I also found this 😊
https://developer.apple.com/documentation/mediaplayer

**Comment by ken89llo** [comment]
This would be awesome! Currently using also "MiniPlay" which is available in the MacApp Store. 
Which bugs were fixed... But this app to be seems very nice. iTunes Support would be the cherry on the cake though.

**Comment by kmikiy** [comment]
How should this work, should it automatically detect which player's info it should show/control (iTunes or Spotify) or should there be a switch somewhere in the app?

I think it would be best if:
If Spotify is open then Spotify is used
If iTunes is open then iTunes is used
If they're both open and none of them or both of them are playing music-> Spotify is preferred
If both are open and only one is playing music -> the one that is playing music (or atleast the last one that was playing music) is used

**Comment by fabi94music** [comment]
Yeah that sound very good. Maybe there could also be an indicator in the widget or menu bar which player is currently used (e.g. Spotify icon or iTunes/Apple Music icon and also the button in the left upper corner of the cover). Or maybe the color of the slider (time) 
<img width="298" alt="bildschirmfoto 2017-07-25 um 11 05 30" src="https://user-images.githubusercontent.com/29753374/28564402-364f8a4e-7129-11e7-8cc9-8afbeea1d6f2.png"> could be blue for iTunes and green for Spotify or something like that. 
Maybe the preferred player if both are open and none playing could be selected in the settings.

**Comment by ken89llo** [comment]
Apple seems to work on its Music Widget as well. But no idea if they support 3rd party apps like Spotify. 
https://9to5mac.com/2017/07/24/macos-high-sierra-beta-4/

**Comment by fabi94music** [comment]
Another interesting project: https://github.com/xzzz9097/Muse

**Comment by Zazerr** [comment]
@fabi94music Nice! if I can ever afford a touch bar Macbook, I'll keep that project in mind! (Looks almost as awesome as Spotmenu :D)

**Comment by fabi94music** [comment]
Any updates on that? :)

**Comment by kmikiy** [comment]
Hey i am currently working on ditching SpotifyAppleScript and using ScriptingBridge instead. I have some working code, but i need to port it to swift 4.0

**Comment by kmikiy** [comment]
initial support for iTunes has been added
[SpotMenu.zip](https://github.com/kmikiy/SpotMenu/files/1545233/SpotMenu.zip)
👆🏻here's a sneak peek

**Comment by kmikiy** [comment]
[SpotMenu.zip](https://github.com/kmikiy/SpotMenu/files/1545688/SpotMenu.zip)
ive improved itunes support

known issue:
- if neither player was playing **before** spotmenu was opened -> play, next, prev buttons dont do anything until music is started manually (by keyboard keys or from the music player)

**Comment by fabi94music** [comment]
It does not open on my Mac. :(

**Comment by kmikiy** [comment]
[SpotMenu.zip](https://github.com/kmikiy/SpotMenu/files/1545864/SpotMenu.zip)
yep, sorry, I just noticed I forgot to embed the music player framework in the app, thats why it didnt open.

**Comment by fabi94music** [comment]
with that version the Notification Center widget freezes and seems not to update anymore.

**Comment by kmikiy** [comment]
Sorry, mea culpa. Easy fix though. 
[SpotMenu.zip](https://github.com/kmikiy/SpotMenu/files/1559445/SpotMenu.zip)

**Comment by fabi94music** [comment]
Thanks, now it doesn't work with iTunes :) The menu bar widget works fine with iTunes :P

**Comment by kmikiy** [comment]
[SpotMenu.zip](https://github.com/kmikiy/SpotMenu/files/1559844/SpotMenu.zip)
>if neither player was playing before spotmenu was opened -> play, next, prev buttons dont do anything until music is started manually (by keyboard keys or from the music player)

fixed this

**Comment by fabi94music** [comment]
sorry to bug you again, but I think this didn't solve the issue I was having. I attached a screenshot. The menu bar widget does well but the notification centre widget seems to struggle 🙈 
![bildschirmfoto 2017-12-14 um 17 04 21](https://user-images.githubusercontent.com/29753374/34001720-06a40ad0-e0f1-11e7-871d-9a8d8968cca9.jpg)

**Comment by kmikiy** [comment]
did you completely delete SpotMenu.app from your Applications folder and replace it with the new version?

**Comment by fabi94music** [comment]
yep, and I even removed it with AppCleaner, that removes additional files.

**Comment by kmikiy** [comment]
does it work with Spotify?

**Comment by fabi94music** [comment]
Yes it works with Spotify 😃 !

**Comment by kmikiy** [comment]
okay, then i know what the problem is. i just need to fix it now 🤦‍♂️

**Comment by kmikiy** [comment]
[SpotMenu.app.zip](https://github.com/kmikiy/SpotMenu/files/1560161/SpotMenu.app.zip)
how about now? this should fix it hopefully 🙏🏻

**Comment by fabi94music** [comment]
Perfect :) Only a quick link to iTunes (in the menu bar widget its the upper left icon on the album art) in the notification center widget would be great :) I have added German translations on the localisation issue :)

**Comment by kmikiy** [comment]
[SpotMenu.app.zip](https://github.com/kmikiy/SpotMenu/files/1562350/SpotMenu.app.zip)
that was a bug 🐛💥🔨
